### ISSUE TITLE
[Question] Server side only?

### ISSUE THREAD

**Issue by chimericdream** [Darkhax-Minecraft/Stuff-A-Sock-In-It#1]
I love the idea of this. I have a modpack for myself and friends, and whenever something goes wrong, digging through log files is a giant pain.

Can this be installed on the server side only, or does it need to be on both client and server due to being a core mod?

**Comment by Darkhax** [comment]
The way the mod is currently coded, clients can use it without the server having it, but the server will require connecting players to have it if the server does. I should be able to fix this rather easily though. I will look into it.

**Comment by chimericdream** [comment]
Cool, thanks!
