### ISSUE TITLE
Continues Sasit Error file

### ISSUE THREAD

**Issue by X-Niter** [Darkhax-Minecraft/Stuff-A-Sock-In-It#13]
I am continuously getting the sasit errored file. 
I am running just the basic filter and it seems that there is no context as to how to add in filters the correct way. 
I went with what your mod description said and tried "word", but that seems to have failed a lot.
I have tried a bunch of combos to attempt to get this to work and nothing. Here are some examples of what I tried. 
< "alternatively" >
<  "dangerous" >
< alternatively >
< dangerous >
The above exampled were all tested by themself without anything else. 
I also tried testing multiple words for it to filter in the following example.
< "alternatively",  "dangerous" >
< alternatively,  dangerous >

Am I adding words in the filter the wrong way? 
Should I be doing < {Word}, {word} > or < [Word], [word] >    ??

Would there be a Wiki that you might have or have been working on that might help? 
Thank you in advance!

**Comment by Naheulf** [comment]
Which versions did you use ? (MC, Forge and SASIT)

Can we assume you try to filter theses lines: ```[08:59:57] [Server thread/WARN] [FML]: Potentially Dangerous alternative prefix `materialis` for name `fairy_ingot`, expected `materialispreload`. This could be a intended override, but in most cases indicates a broken mod.```

**Comment by X-Niter** [comment]
I'm going to be honest, I gave up on the whole things and moved on, left this here thinking it might spark up a potential wiki for the common users to get an understanding.

Although, Yes that's correct to assume.
