### ISSUE TITLE
1.14.4 Configuring Issues

### ISSUE THREAD

**Issue by Osprey4444** [Darkhax-Minecraft/Stuff-A-Sock-In-It#14]
Hello,

I was wondering how to configure the 1.14.4 config? I seem to be having issues with it due to its different formatting compared to the 1.12.2 config, how would I make the 1.14.4 config remove the same messages as my 1.12.2?

1.12.2 – https://hastebin.com/jubisocoro.coffeescript

1.14.4 - https://hastebin.com/ayasogepuk.coffeescript

**Comment by Darkhax** [comment]
Forge changed the config spec in 1.13+. You can not use the same config file. Look for the toml file and edit that one. Also in toml strings values require quotes around them.
