### ISSUE TITLE
How to filter?

### ISSUE THREAD

**Issue by DCCross** [Darkhax-Minecraft/Stuff-A-Sock-In-It#18]
Hi,I try to filter "null" and "dangerous but it doesn't work, 

could you give me an example of how to filter?

Config:
general {
    # A list of strings. If a console message contains any of these, it will be filtered out of the log. [default: ]
    S:BasicFilter < "null""dangerous"
     >

**Comment by Darkhax** [comment]
In old versions of Forge String lists are not quoted and use new line instead. 

```
S:BasicFilter <
    null
    dangerous
>
