### ISSUE TITLE
Whitelist option for config

### ISSUE THREAD

**Issue by IronPiston** [Darkhax-Minecraft/Stuff-A-Sock-In-It#5]
Would you be able to implement a whitelist option in the config, so I can have the console only display specific messages?

**Comment by Darkhax** [comment]
Thanks for the issue request. This is possible to do, however it doesn't make too much sense to do. Crash reports can not be accurately detected by a filter, so they will be destroyed in whitelist mode. This would make tracking down crashes and other things really hard to do.
