### ISSUE TITLE
Request for Examples

### ISSUE THREAD

**Issue by LarcekGiglamesh** [Darkhax-Minecraft/Stuff-A-Sock-In-It#6]
Dear @Darkhax ,

we're really interested in your SASIT mod but it doesn't come with any documentation or examples, which makes it hard to define the list correctly. 

when running modpacks that change or disable recipes one frequent error we receive is:

> [01:48:50] [Server thread/ERROR] [net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft:recipes/brewing/brewing_stand
> com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:brewing_stand'

which comes with a stacktrace of around 25 lines. we'd like to remove those but all attempts, whether using a substring like "Parsing error loading built-in advancement" or ones using whitespaces or regex just doesn't seem to catch the errors and hiding them. 

Could you share a few Examples for setting up your Config to correctly catch such console messages? 

Thanks

**Comment by Darkhax** [comment]
Hello, 

This mod currently uses substring matching to search for invalid log entries. So in the case of that message `Parsing error loading built-in advancement` should be enough to catch them all. The config for this would look like 

```
general {
    # A list of strings. If a console message contains any of these, it will be filtered out of the log. [default: [Parsing error loading built-in advancement]]
    S:BasicFilter <
        Parsing error loading built-in advancement
     >
}
```

I've gone ahead and tested / confirmed that this mod and configuration works with Forge `14.23.5.2838`. I've wanted to add regex filters for a while now and they will also likely be in a future release.

**Comment by Darkhax** [comment]
Now that I have provided examples, and released an update with REGEX support I will be closing this issue. If you have any further questions or requests feel free to comment or open another issue.
