### ISSUE TITLE
[1.14.4] Crash on load- config, RuntimeException, NPE, .ExceptionInInitializerError

### ISSUE THREAD

**Issue by ProsperCraft** [Darkhax-Minecraft/Stuff-A-Sock-In-It#7]
https://gist.github.com/ProsperCraft/f687795f6be470241809314b3a0f1629

This was on first load, tried a second got the same result.

Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

StuffASockInIt-1.14.4-3.0.1
forge-1.14.4-28.0.29

**Comment by Darkhax** [comment]
Thanks for the report. I've released an update on 1.13.3 and 1.14.4 which fixes this issue. Let me know if you have further issues.
